// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace DecompressionML.Model
{
    public class ModelInput
    {
        [ColumnName("P1"), LoadColumn(0)]
        public float P1 { get; set; }


        [ColumnName("P2"), LoadColumn(1)]
        public float P2 { get; set; }


        [ColumnName("P3"), LoadColumn(2)]
        public float P3 { get; set; }


        [ColumnName("ResRisk"), LoadColumn(3)]
        public float ResRisk { get; set; }


    }
}
